// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/system.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileReq) Reset() {
	*x = SendFileReq{}
	mi := &file_api_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileReq) ProtoMessage() {}

func (x *SendFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileReq.ProtoReflect.Descriptor instead.
func (*SendFileReq) Descriptor() ([]byte, []int) {
	return file_api_system_proto_rawDescGZIP(), []int{0}
}

func (x *SendFileReq) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type SendFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResp) Reset() {
	*x = SendFileResp{}
	mi := &file_api_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResp) ProtoMessage() {}

func (x *SendFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResp.ProtoReflect.Descriptor instead.
func (*SendFileResp) Descriptor() ([]byte, []int) {
	return file_api_system_proto_rawDescGZIP(), []int{1}
}

func (x *SendFileResp) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_api_system_proto protoreflect.FileDescriptor

const file_api_system_proto_rawDesc = "" +
	"\n" +
	"\x10api/system.proto\x12\x06system\"*\n" +
	"\vSendFileReq\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"(\n" +
	"\fSendFileResp\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2H\n" +
	"\rSystemService\x127\n" +
	"\bSendFile\x12\x13.system.SendFileReq\x1a\x14.system.SendFileResp0\x01B\tZ\a/systemb\x06proto3"

var (
	file_api_system_proto_rawDescOnce sync.Once
	file_api_system_proto_rawDescData []byte
)

func file_api_system_proto_rawDescGZIP() []byte {
	file_api_system_proto_rawDescOnce.Do(func() {
		file_api_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_system_proto_rawDesc), len(file_api_system_proto_rawDesc)))
	})
	return file_api_system_proto_rawDescData
}

var file_api_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_system_proto_goTypes = []any{
	(*SendFileReq)(nil),  // 0: system.SendFileReq
	(*SendFileResp)(nil), // 1: system.SendFileResp
}
var file_api_system_proto_depIdxs = []int32{
	0, // 0: system.SystemService.SendFile:input_type -> system.SendFileReq
	1, // 1: system.SystemService.SendFile:output_type -> system.SendFileResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_system_proto_init() }
func file_api_system_proto_init() {
	if File_api_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_system_proto_rawDesc), len(file_api_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_system_proto_goTypes,
		DependencyIndexes: file_api_system_proto_depIdxs,
		MessageInfos:      file_api_system_proto_msgTypes,
	}.Build()
	File_api_system_proto = out.File
	file_api_system_proto_goTypes = nil
	file_api_system_proto_depIdxs = nil
}
