sql:
  dsn: "postgres://admin:admin@postgres:5432/taxin?sslmode=disable"

redis:
  address: "redis:6379"
  username: ""
  password: ""
  db: 0

jeager:
  address: "jaeger-all-in-one:4317"

ollama:
  address: "http://ollama:11434/api/embeddings"
  model: "chroma/all-minilm-l6-v2-f32:latest"
